### ISSUE TITLE
SegFault in R using XML processed by pdftohtml

### ISSUE THREAD

**Issue by mespe** [dsidavis/pdftohtml#2]
XML from ReadPDF::convertPDF2XML causes segfault when produced from mclapply. This occurs only with the latest changes, and does not occur with the previous commits.

# Reproducible steps

```
# sp.pdf is created in setup.R in top level of Zoonotics dir  

 > sp_xml = mclapply(sp.pdf, function(x) try(convertPDF2XML(x)), mc.cores = 64L) 
 > names(sp_xml) = sp.pdf
!> sp_xml[[1]]

  *** caught segfault ***
 address 0x8, cause 'memory not mapped'

 Traceback:
  1: .Call("R_getDocEncoding", obj, PACKAGE = "XML")
  2: getEncoding(doc)
  3: getEncoding(doc)
  4: saveXML(from)
  5: saveXML(from)
  6: asMethod(object)
  7: as(x, "character")
  8: cat(as(x, "character"), "\n")
  9: print.XMLInternalDocument(x)
 10: function (x, ...) UseMethod("print")(x)

```

**Comment by dsidavis** [comment]
That should never do what you want it to.  convertPDF2XML returns the parsed document which an external pointer.  When that is returned by the worker process, the value of the external pointer should be 0, i.e. NULL in C.  And it is. So R_getDocEncoding is screwing up.
I've pushed a change to the XML package on github.  But sp_xml should all be empty PDF documents.

**Comment by mespe** [comment]
Calling sp_xml[[1]] was the shortest way to trigger the error.

I was originally getting it with calling getSectionText, which should take the pointer without issue.
